version: "2"

services:
  sdk-build-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: checkout-sdk-web
    command:
      - npm
      - run
      - build
    volumes:
      - ./dist:/usr/sdk/dist

  sdk-test-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: checkout-sdk-web
    command:
      - npm
      - test
    expose:
      - 9876
    volumes:
      - ./coverage:/usr/sdk/coverage

  githook-installer:
    build:
      context: ./
      dockerfile: "githooks.Dockerfile"
    volumes:
      - ./.git:/tmp/.git
      - ./hooks:/tmp/hooks
