version: "2"

services:
  sdk-build-runner:
    depends_on:
      - githook-installer

  sdk-build-watcher:
    build:
      context: ./
      dockerfile: Dockerfile
    image: checkout-sdk-web
    command:
      - npm
      - start
    volumes:
      - ./src:/usr/sdk/src
      - ./dist:/usr/sdk/dist
    depends_on:
      - githook-installer

  sdk-test-runner:
    depends_on:
      - githook-installer

  sdk-test-watcher:
    build:
      context: ./
      dockerfile: Dockerfile
    image: checkout-sdk-web
    command:
      - npm
      - run
      - test:watch
    expose:
      - 9876
    volumes:
      - ./src:/usr/sdk/src
      - ./test:/usr/sdk/test
    depends_on:
      - githook-installer
